### PR TITLE
Resource Graph Driver

### PR DESCRIPTION
**Pull request by rcobb-scwx**
Branch that adds resource graph driver to msticpy -- #162

### CODE REVIEW

**Comment by petebryan** [comment]
@rcobb-scwx thanks for the submission, it works great. I've made a few minor changes to the driver and added some extra test coverage and documentation - its all in https://github.com/rcobb-scwx/msticpy/pull/1 - take a look when you get a chance and see what you think.

**Comment by ianhelle** [comment]
Branch moved into #167 and merged into main

**Pull request closed without merging**
