### PR TITLE
Cybereason

### PR DESCRIPTION
**Pull request by FlorianBracq**
Answers #305 but requires #285 and #291 to work as expected.

### CODE REVIEW

**Review by petebryan — APPROVED** [review]
Test should pass once https://github.com/microsoft/msticpy/pull/291 merged  in. Will do that and confirm.

**Comment by petebryan** [comment]
@FlorianBracq one additional thing, could we ask that you please add a short documentation page under docs/source/data_acquisiton. Just something very short to show users how to access the use the provider.

**Comment by petebryan** [comment]
Thanks for the docs @FlorianBracq - looks like you have an issue with the Cybereason tests. It looks like the mocked data in the test has this format:
                "elementValues": {
                    "users": {
                        "totalValues": 5,
                        "elementValues": [],
                        "totalSuspicious": 0,
                        "totalMalicious": 0,
                        "guessedTotal": 0,
                    }
 But the driver looks for a "values" key in there. Not sure if this is a mocked data or a driver issue here.

**Comment by FlorianBracq** [comment]
> Thanks for the docs @FlorianBracq - looks like you have an issue with the Cybereason tests. It looks like the mocked data in the test has this format: "elementValues": { "users": { "totalValues": 5, "elementValues": [], "totalSuspicious": 0, "totalMalicious": 0, "guessedTotal": 0, } But the driver looks for a "values" key in there. Not sure if this is a mocked data or a driver issue here.

@petebryan: that was a PEBKAC ;)

**Review by petebryan — APPROVED** [review]

**Pull request merged**
