### PR TITLE
Add support for Python 3.10, 3.11 and test in CI

### PR DESCRIPTION
**Pull request by tonybaloney**
This PR updates the tests to a matrix to try all supported versions of Python (according to the specifiers for this package).

IT also adds 3.11 for good measure.

I split out all the linting tasks into a separate jobs so they only run once per workflow, not per matrix item

### CODE REVIEW

**Comment by tonybaloney** [comment]
Uncovers a compatibility issue with one of the dependencies in 3.10+.
Will raise a separate issue

**Comment by tonybaloney** [comment]
mo-sql-parsing is the replacement package

**Comment by tonybaloney** [comment]
```python
>>> sql="""
...         SELECT DISTINCT ParentMessage as mssg, COUNT(Otherfield)
...         FROM (SELECT EventID as ID, ParentImage, Image, Message,
...             ParentImage + Message as ParentMessage,
...             LOWER(Otherfield) FROM apt29Host
...             )
...         WHERE Channel = "Microsoft-Windows-Sysmon/Operational"
...             AND EventID = 1
...             AND LOWER(ParentImage) LIKE "%explorer.exe"
...         """
>>> import moz_sql_parser
>>> moz_sql_parser.parse(sql)
{'select': {'value': {'distinct': [{'value': 'ParentMessage', 'name': 'mssg'}, {'value': {'count': 'Otherfield'}}]}}, 'from': {'value': {'select': [{'value': 'EventID', 'name': 'ID'}, {'value': 'ParentImage'}, {'value': 'Image'}, {'value': 'Message'}, {'value': {'add': ['ParentImage', 'Message']}, 'name': 'ParentMessage'}, {'value': {'lower': 'Otherfield'}}], 'from': 'apt29Host'}}, 'where': {'and': [{'eq': ['Channel', 'Microsoft-Windows-Sysmon/Operational']}, {'eq': ['EventID', 1]}, {'like': [{'lower': 'ParentImage'}, '%explorer\\.exe']}]}}
>>> sql="""
...         SELECT DISTINCT ParentMessage as mssg, COUNT(Otherfield)
...         FROM (SELECT EventID as ID, ParentImage, Image, Message,
...             ParentImage + Message as ParentMessage,
...             LOWER(Otherfield) FROM apt29Host
...             )
...         WHERE Channel = "Microsoft-Windows-Sysmon/Operational"
...             AND EventID = 1
...             AND LOWER(ParentImage) LIKE "%explorer.exe"
...         """
>>> mo_sql_parsing.parse(sql)
{'select_distinct': [{'value': 'ParentMessage', 'name': 'mssg'}, {'value': {'count': 'Otherfield'}}], 'from': {'select': [{'value': 'EventID', 'name': 'ID'}, {'value': 'ParentImage'}, {'value': 'Image'}, {'value': 'Message'}, {'value': {'add': ['ParentImage', 'Message']}, 'name': 'ParentMessage'}, {'value': {'lower': 'Otherfield'}}], 'from': 'apt29Host'}, 'where': {'and': [{'eq': ['Channel', 'Microsoft-Windows-Sysmon/Operational']}, {'eq': ['EventID', 1]}, {'like': [{'lower': 'ParentImage'}, '%explorer..exe']}]}}
```

They return different data structures so this change would be more complicated than thought

**Comment by ianhelle** [comment]
Hey Anthony, this all arrived as I was getting on a plane for a vacation.
I've been aware of the mo-sql-parser issue for a while. Until recently, we needed to support Python 3.6 and the pinned version for this package was the last to support Py3.6.
Somewhat annoyingly, the AST format output by the tool seems to change with each version so I need to track specific versions of the parser and modify our code for that version's AST format. I have this as a ToDo but it may be a little while before I can get to it.

A shorter-term workaround would be to drop the unit the test for PyVer >= 3.10 and have trap around the import of mo-sql-parser in our code that fails if Python >= 3.10.

**Comment by tonybaloney** [comment]
The old parser doesn't work with Python 3.10+

```
---
[109](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:110)
Exception was raised by:
[110](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:111)
Traceback (most recent call last):
[111](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:112)

[112](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:113)
  File "/home/runner/work/msticpy/msticpy/msticpy/data/sql_to_kql.py", line 34, in <module>
[113](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:114)
    import moz_sql_parser
[114](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:115)

[115](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:116)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/moz_sql_parser/__init__.py", line 15, in <module>
[116](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:117)
    from moz_sql_parser.sql_parser import SQLParser, scrub_literal, scrub
[117](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:118)

[118](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:119)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/moz_sql_parser/sql_parser.py", line 12, in <module>
[119](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:120)
    from mo_parsing.engine import Engine
[120](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:121)

[121](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:122)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mo_parsing/__init__.py", line 122, in <module>
[122](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:123)
    from mo_parsing.expressions import And, Each, MatchFirst, Or, ParseExpression
[123](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:124)

[124](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:125)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mo_parsing/expressions.py", line 746, in <module>
[125](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:126)
    from mo_parsing import helpers
[126](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:127)

[127](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:128)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/mo_parsing/helpers.py", line 4, in <module>
[128](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:129)
    from collections import Iterable
[129](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:130)

[130](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:131)
ImportError: cannot import name 'Iterable' from 'collections' (/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/collections/__init__.py)
[131](https://github.com/microsoft/msticpy/runs/7422854806?check_suite_focus=true#step:10:132)
```

**Comment by ianhelle** [comment]
I think the right thing to do is fix the code and switch to the latest version. AST doesn't seem to have changed that much.
The feature is billed as experimental and the sql-kql stuff is an extra but I think the workaround might be almost as much trouble as doing the right thing (famous last words)

**Comment by ianhelle** [comment]
@tonybaloney 
I've just opened a PR (#488) that switches moz-sql-parser for mo-sql-parsing and fixed the code based on the new AST schema.
One this completes, we should have removed the Py 3.10 compatibility issue and we can remerge this branch which (hopefully) will build beautifully, and we'll be able to leap forward into a brighter and cleaner future. :-D

**Review by ianhelle — DISMISSED** [review]

**Comment by ianhelle** [comment]
@tonybaloney - I've merged the changes for mo-sql-parsing and re-merged main with this PR.
I wasn't 100 sure why your package version for mo-sql-parsing was <8.xx;>9.0.0 - is that just being conservative in case there are breaking changes in 9.0.0?
The merge has reverted most of the changes to the sql2kql module that you made - mainly a few things in BINARY_OPS. It seems to work OK.

Anyway - huge thanks for the Python 3.9+ matrix changes as well as the doc and notebook changes that you made for these - seems above and beyond the call but I'm very grateful. :-)

**Comment by tonybaloney** [comment]
> @tonybaloney - I've merged the changes for mo-sql-parsing and re-merged main with this PR. I wasn't 100 sure why your package version for mo-sql-parsing was <8.xx;>9.0.0 - is that just being conservative in case there are breaking changes in 9.0.0? The merge has reverted most of the changes to the sql2kql module that you made - mainly a few things in BINARY_OPS. It seems to work OK.
> 
> Anyway - huge thanks for the Python 3.9+ matrix changes as well as the doc and notebook changes that you made for these - seems above and beyond the call but I'm very grateful. :-)

Yes, I was being conservative pinning a range 8.x - 9.0

I'll rebase this PR against main so it'll hopefully clear up the failures.

**Comment by tonybaloney** [comment]
Build failure:

```
Collecting setoptconf<0.3.0,>=0.2.0
[221](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:222)
  Downloading setoptconf-0.2.0.tar.gz (13 kB)
[222](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:223)
  Preparing metadata (setup.py): started
[223](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:224)
  Preparing metadata (setup.py): finished with status 'error'
[224](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:225)
  error: subprocess-exited-with-error
[225](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:226)
  
[226](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:227)
  × python setup.py egg_info did not run successfully.
[227](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:228)
  │ exit code: 1
[228](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:229)
  ╰─> [1 lines of output]
[229](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:230)
      error in setoptconf setup command: use_2to3 is invalid.
[230](https://github.com/microsoft/msticpy/runs/8165408073?check_suite_focus=true#step:8:231)
      [end of output]
``` 

Apparently setuptools >58 breaks support for use_2to3, which setoptconf uses. Setoptconf 0.2.0 is also 8 years old and the newer version 0.3.0 likely fixes this if we can first work out where the dependancy came from

**Review by petebryan — APPROVED** [review]

**Comment by petebryan** [comment]
This appeared to be building successfully in branch but immediately caused the use_2to3 issue in Main so I've reverted the merge.

**Comment by petebryan** [comment]
This appeared to be building successfully in branch but immediately caused the use_2to3 issue in Main so I've reverted the merge.

image

**Comment by ianhelle** [comment]
I think setoptconf is a dynamic dependency of propector - in that it isn't declare as a dependency in setup.
It looks like they (prospector) created a fork of this call setoptconf-tmp but I'm not sure that this is reliably installing and seems to revert to the original broken one.

The issue with py 3.11 is something else though - it seems to die when installing SciPy - again due to a setup error. Not sure how to solve that.

**Pull request merged**
