### PR TITLE
RiskIQ threat intel provider & pivots

### PR DESCRIPTION
**Pull request by aeetos**
Offers a new threat intel provider for RiskIQ Illuminate and RiskIQ PassiveTotal APIs. 

Proposes a new way to register pivot functions provided by threat intel providers. Registers a set of pivot functions for RiskIQ datasets on hostname, FQDN and IPAddress entities.

Adds optional dependency on RiskIQ-built `passivetotal` package, activated by a `riskiq` pip extra.

Known Issues:
- Tests are not built yet; would appreciate guidance on how best to mock tests for online providers. 
- Unsure where to document RiskIQ-specific keys needed in `msticpyconfig.yaml` (see example below for testing purposes)
- Docs for `riskiq` extra and other capabilities are not written yet, need guidance on where that should go.

Config example for RiskIQ provider:
```
  RiskIQ:
    Args:
      ApiUsername: "user@host.com"
      AuthKey: "     "
    Provider: "RiskIQ"
    Primary: True
```

### CODE REVIEW

**Comment by ianhelle** [comment]
Thanks Mark - that's fabulous.
Give me a few days to take a look. About to go on vacation and am a bit slammed with things.
Looks like you need to sign the Contributor License Agreement (see above). Not exactly sure what the details of this are.

**Comment by aeetos** [comment]
No worries! I have that legal agreement in queue for review. Enjoy your vacation, we can sync up when you return.

**Comment by petebryan** [comment]
Hi @aeetos - sorry for the delay in this, its taken me a while to get to whilst Ian is out. The PR is looking great. In response to your specific questions:

Docs for riskiq extra and other capabilities are not written yet, need guidance on where that should go.
 - https://github.com/microsoft/msticpy/blob/master/docs/source/getting_started/Installing.rst has a table which details all of the extras options so this would be the best place.
 
 Unsure where to document RiskIQ-specific keys needed in msticpyconfig.yaml (see example below for testing purposes)
 - https://github.com/microsoft/msticpy/blob/master/docs/source/getting_started/msticpyconfig.rst and https://github.com/microsoft/msticpy/blob/master/docs/source/data_acquisition/TIProviders.rst have sample configs, simply adding an RiskIQ section in there should be sufficient.
 
Tests are not built yet; would appreciate guidance on how best to mock tests for online providers.
 -For this our approach has generally been to mock the response from the provider and validate that responses are processed correctly. You can see a set of simple examples here: https://github.com/microsoft/msticpy/blob/master/tests/test_tiproviders.py
Obviously in this case you are needing to mock the response from ptanalyzer which is a bit more complicated than these ones but I think should follow the same pattern. I am not an expert of mocks but let me know if you need help as I have some experience here.

**Comment by aeetos** [comment]
Thanks for the direction, @petebryan - I've submitted a new commit that should provide the documentation and example config file, plus a unit test for our provider and some bug fixes. We've also added support for a header to be sent with API requests that help us with metrics and diagnostics, so that's included as well now.

I've also accepted the CLA. 

Let me know what else I can help with here, and thanks again for looking at this!

**Comment by 2xyo** [comment]
Hi, I tested this PR and I have just a minor issue with a timeout.

Installation:
```console
cd $(mktemp -d)
git clone https://github.com/microsoft/msticpy.git 
cd msticpy
git fetch origin pull/175/head:riskiq
git checkout riskiq
python3 -m venv .venv --prompt="RiskIq"
source .venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade wheel setuptools
# temp fix https://github.com/PyCQA/prospector/issues/442 
python3 -m pip install https://github.com/PyCQA/prospector/archive/refs/heads/master.zip
python3 -m pip install -e .[riskiq]
python3 -m pip install -e .[all]
python3 -m pip install -e .[dev]
python3 -m pip install pre-commit   # missing in requierment-dev 
pre-commit install
```

CI tests
```console
$ pre-commit run --from-ref origin/HEAD --to-ref riskiq
...
pylint...................................................................Failed
- hook id: pylint
- exit code: 20

************* Module msticpy.sectools.tiproviders.riskiq
msticpy/sectools/tiproviders/riskiq.py:302:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
msticpy/sectools/tiproviders/riskiq.py:303:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
msticpy/sectools/tiproviders/riskiq.py:304:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
msticpy/sectools/tiproviders/riskiq.py:305:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)

...
$ pytest -k "riskiq"
...
tests/sectools/test_tiproviders.py . [100%]
...
```

Manal test in notebook
```console 
python -m ipykernel install --user --name=.venv
cd $(mktemp -d) 
jupyter-lab
```

In the notebook with the good kernel:

```py

%%writefile msticpyconfig.yaml
QueryDefinitions:

TIProviders:
  RiskIQ:
    Args:
      ApiID: "redacted>"
      AuthKey: "<redacted>"
    Provider: "RiskIQ"
    Primary: True
```

```py
from msticpy.sectools import TILookup
TILookup.list_available_providers(show_query_types=True)
```

```output
RiskIQ
RiskIQ Threat Intelligence Lookup. Supported query types:
	ioc_type=dns
	ioc_type=dns, ioc_query_type=articles
	ioc_type=dns, ioc_query_type=artifacts
	ioc_type=dns, ioc_query_type=certificates
	ioc_type=dns, ioc_query_type=components
	ioc_type=dns, ioc_query_type=cookies
	ioc_type=dns, ioc_query_type=hostpairchildren
	ioc_type=dns, ioc_query_type=hostpairparents
	ioc_type=dns, ioc_query_type=malware
	ioc_type=dns, ioc_query_type=passivedns
	ioc_type=dns, ioc_query_type=projects
	ioc_type=dns, ioc_query_type=rep
	ioc_type=dns, ioc_query_type=summary
	ioc_type=dns, ioc_query_type=trackers
	ioc_type=dns, ioc_query_type=whois
	ioc_type=hostname
	ioc_type=hostname, ioc_query_type=articles
	ioc_type=hostname, ioc_query_type=artifacts
	ioc_type=hostname, ioc_query_type=certificates
	ioc_type=hostname, ioc_query_type=components
	ioc_type=hostname, ioc_query_type=cookies
	ioc_type=hostname, ioc_query_type=hostpairchildren
	ioc_type=hostname, ioc_query_type=hostpairparents
	ioc_type=hostname, ioc_query_type=malware
	ioc_type=hostname, ioc_query_type=passivedns
	ioc_type=hostname, ioc_query_type=projects
	ioc_type=hostname, ioc_query_type=rep
	ioc_type=hostname, ioc_query_type=summary
	ioc_type=hostname, ioc_query_type=trackers
	ioc_type=hostname, ioc_query_type=whois
	ioc_type=ipv4
	ioc_type=ipv4, ioc_query_type=articles
	ioc_type=ipv4, ioc_query_type=artifacts
	ioc_type=ipv4, ioc_query_type=certificates
	ioc_type=ipv4, ioc_query_type=components
	ioc_type=ipv4, ioc_query_type=cookies
	ioc_type=ipv4, ioc_query_type=hostpairchildren
	ioc_type=ipv4, ioc_query_type=hostpairparents
	ioc_type=ipv4, ioc_query_type=malware
	ioc_type=ipv4, ioc_query_type=passivedns
	ioc_type=ipv4, ioc_query_type=projects
	ioc_type=ipv4, ioc_query_type=rep
	ioc_type=ipv4, ioc_query_type=services
	ioc_type=ipv4, ioc_query_type=summary
	ioc_type=ipv4, ioc_query_type=trackers
	ioc_type=ipv4, ioc_query_type=whois
```
 :+1: 


Test from https://msticpy.readthedocs.io/en/latest/data_acquisition/TIProviders.html#looking-up-iocs 
```py
ti_lookup = TILookup(providers=["RiskIQ"])
result, details = ti_lookup.lookup_ioc(observable="38.75.137.9")
print("Positive" if result else "Negative")
# the details is a list (since there could be multiple responses for an IoC)
for provider, detail in details:
    print(provider)
    detail.summary
    print("\nRaw Results")
    detail.raw_result_fmtd
```
:+1: 


```py
result = ti_lookup.lookup_ioc(observable="38.75.137.9", providers=["RiskIQ"])
ti_lookup.result_to_df(result).T
```
:+1:


```py
ioc_ips = [
    "185.92.220.35",
    "213.159.214.86",
    "77.222.54.202",
    "91.219.29.81",
    "193.9.28.254",
    "89.108.83.196",
    "91.219.28.44",
    "188.127.231.124",
    "192.42.116.41",
    "91.219.31.18",
    "46.4.239.76",
    "188.166.168.250",
    "195.154.241.208",
    "51.255.172.55",
    "93.170.169.52",
    "104.215.148.63",
    "13.77.161.179",
    "40.76.4.15",
    "40.112.72.205",
    "40.113.200.201",
]

ti_lookup.lookup_iocs(data=ioc_ips, providers="RiskIQ")
```

output 
```
ReadTimeout: HTTPSConnectionPool(host='api.passivetotal.org', port=443): Read timed out. (read timeout=30)
```

Any tips to increase the timeout?

**Comment by aeetos** [comment]
Hi! Thanks for testing!

> ```
> ReadTimeout: HTTPSConnectionPool(host='api.passivetotal.org', port=443): Read timed out. (read timeout=30)
> ```
> 
> Any tips to increase the timeout?

Hmm, the 30 second timeout should be plenty for each of the API calls that are happening here (two calls per IOC, one for summary data and one for reputation score). If you're getting timeouts, try repeating the query (it worked for me but it did take a while), and if it continues to happen, we need to log a ticket to investigate the API itself. 

Meanwhile, I'll consider whether there's a clean way within this library to bring a timeout value from the yaml config and push it all the way to our `analyzer` module.

**Review by ianhelle — DISMISSED** [review]

**Review by ianhelle — DISMISSED** [review]

**Review by ianhelle — APPROVED** [review]
I've tested locally. I think the failures in CI are because it cannot access the pipeline secrets.
If you're happy, I will merge it.

**Comment by aeetos** [comment]
Yep, I'm good - agreed, it does look like it's just a geoip database issue. I can commit to addressing the `pylint` issues in a follow-up PR at a later date.

**Comment by ianhelle** [comment]
Some pipeline tests are failing but this is due to the PR being external (i.e. doens't have access to pipeline secrets)
Have tested locally and test all pass.

**Pull request merged**
